#+title: Paweł Bartkiewicz's Emacs configuration
#+startup: showeverything

* About this file

After many years of creating new =init.el= files from scratch on each machine I used (because old
ones somehow weren't portable and were so degenerate I didn't want to fix them) I finally decided
to organise my Emacs configuration properly. This is the result. It is heavily influenced by
[[https://github.com/sachac/.emacs.d/][Sacha Chua's Org mode-based .emacs.d]]. This is also my first foray into literate programming using
[[https://orgmode.org][Org mode]]. Even if not useful to anyone else, I do hope it will help me remember the purpose of each
elisp snippet I add here.

I'm starting by creating an almost empty Org file and keeping my old config as =legacy.el=.
I will slowly move code here over time.

* Header

Make sure we're using UTF-8. Also set Org's =:padline= to =no= here to avoid generating an empty
line at the beginning of the file (who would ever want to begin a file with an empty line?!).

#+begin_src emacs-lisp :tangle yes :padline no
  ;; -*- coding: utf-8 -*-
#+end_src

* Basic settings

** Remove visual clutter

I don't want all this clutter. Disable tool bars, menu bars and scroll bars.

#+begin_src emacs-lisp :tangle yes
  (tool-bar-mode -1)
  (menu-bar-mode -1)
  (scroll-bar-mode -1)
#+end_src

The startup screen is nice, but I don't need it.

#+begin_src emacs-lisp :tangle yes
  (setq inhibit-startup-screen t)
#+end_src

** Security

Never use unsafe file local variables, especially =eval=.

#+begin_src emacs-lisp :tangle yes
  (setq enable-local-variables :safe
        enable-local-eval nil)
#+end_src

* Load =legacy.el=

#+begin_src emacs-lisp :tangle yes
  (load "~/.emacs.d/legacy.el")
#+end_src
